oar_config_2clusters:
 - update_hostfile2:
   - append_file:
     - /etc/hosts
     - |
       127.0.0.2 node1 node2
 - hosts_check_startup2:
   - append_file: 
     - /etc/default/oar-server
     - |
       cat /etc/hosts | grep pode1 >/dev/null|| echo '127.0.0.3 pode pode1 pode2 ' >> /etc/hosts
 - create_resources2:
   - exec_chroot: oarproperty -a cluster -c
   - exec_chroot: oarnodesetting -a -h pode1 -p cpu=4 -p core=8 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode1 -p cpu=4 -p core=9 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode1 -p cpu=4 -p core=10 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode1 -p cpu=4 -p core=11 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode1 -p cpu=5 -p core=12 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode1 -p cpu=5 -p core=13 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode1 -p cpu=5 -p core=14 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode1 -p cpu=5 -p core=15 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode2 -p cpu=6 -p core=16 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode2 -p cpu=6 -p core=17 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode2 -p cpu=6 -p core=18 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode2 -p cpu=6 -p core=19 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode2 -p cpu=7 -p core=20 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode2 -p cpu=7 -p core=21 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode2 -p cpu=7 -p core=22 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h pode2 -p cpu=7 -p core=23 -p cpuset=0
   - exec_chroot: oarnodesetting -p cluster=nodes --sql "network_address like 'node%'"
   - exec_chroot: oarnodesetting -p cluster=podes --sql "network_address like 'pode%'"
