oar_config_2clusters:
 - update_hostfile2:
   - append_file:
     - /etc/hosts
     - |
       127.0.0.2 tchernobyl tchernobyl1 tchernobyl2 tchernobyl3
       127.0.0.3 threemile threemile1 threemile2 threemile3
       127.0.0.4 fukushima fukushima1 fukushima2 fukushima3
 - create_resources2:
   - exec_chroot: oarproperty -a cluster -c
   - exec_chroot: oarnodesetting -a -h tchernobyl1 -p cpu=4 -p core=8 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl1 -p cpu=4 -p core=9 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl1 -p cpu=4 -p core=10 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl1 -p cpu=4 -p core=11 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl1 -p cpu=5 -p core=12 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl1 -p cpu=5 -p core=13 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl1 -p cpu=5 -p core=14 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl1 -p cpu=5 -p core=15 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl2 -p cpu=6 -p core=16 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl2 -p cpu=6 -p core=17 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl2 -p cpu=6 -p core=18 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl2 -p cpu=6 -p core=19 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl2 -p cpu=7 -p core=20 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl2 -p cpu=7 -p core=21 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl2 -p cpu=7 -p core=22 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h tchernobyl2 -p cpu=7 -p core=23 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h fukushima1 -p cpu=8 -p core=24 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h fukushima1 -p cpu=8 -p core=25 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h fukushima1 -p cpu=9 -p core=26 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h fukushima1 -p cpu=9 -p core=27 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h fukushima2 -p cpu=10 -p core=28 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h fukushima2 -p cpu=10 -p core=29 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h fukushima2 -p cpu=11 -p core=30 -p cpuset=0
   - exec_chroot: oarnodesetting -a -h fukushima2 -p cpu=11 -p core=31 -p cpuset=0
   - exec_chroot: oarnodesetting -p cluster=threemile --sql "network_address like 'node%'"
   - exec_chroot: oarnodesetting -p cluster=fukushima --sql "network_address like 'fukushima%'"
   - exec_chroot: oarnodesetting -p cluster=tchernobyl --sql "network_address like 'tchernobyl%'"
